centos_build:
  stage: build
  tags:
    - centos
  artifacts:
    paths:
      - ./openfpm_data/build/src/mem_map
  script:
    - ./build.sh $CI_PROJECT_DIR $CI_RUNNER_TAGS NO $CI_COMMIT_REF_NAME

centos_run:
  stage: test
  tags:
    - centos
  dependencies:
    - centos_build
  script:
    - ./openfpm_data/build/src/mem_map

mac_build:
  stage: build
  tags:
    - mac
  artifacts:
    paths:
      - ./openfpm_data/build/src/mem_map
  script:
    - ./build.sh $CI_PROJECT_DIR $CI_RUNNER_TAGS NO $CI_COMMIT_REF_NAME

mac_run:
  stage: test
  tags:
    - mac
  dependencies:
    - mac_build
  script:
    - ./openfpm_data/build/src/mem_map 

ubuntu_build:
  stage: build
  tags:
    - ubuntu
  artifacts:
    paths:
      - ./openfpm_data/build/src/mem_map
  script:
    - ./build.sh $CI_PROJECT_DIR $CI_RUNNER_EXECUTABLE_TAGS NO $CI_COMMIT_REF_NAME

ubuntu_run:
  stage: test
  tags:
    - ubuntu
  dependencies:
    - ubuntu_build
  script:
    - ./openfpm_data/build/src/mem_map

