centos_build:
  stage: build
  tags:
    - centos
  artifacts:
    paths:
<<<<<<< HEAD
      - ./openfpm_data/build/src/mem_map
=======
      - ./openfpm_io/build/src/io
      - ./openfpm_io/test_data
>>>>>>> origin/master
  script:
    - ./build.sh $CI_PROJECT_DIR $CI_RUNNER_TAGS NO $CI_COMMIT_REF_NAME

centos_run:
  stage: test
  tags:
    - centos
  dependencies:
    - centos_build
  script:
<<<<<<< HEAD
    - ./openfpm_data/build/src/mem_map
=======
    - ./run.sh $CI_PROJECT_DIR $CI_RUNNER_TAGS NO $CI_COMMIT_REF_NAME
>>>>>>> origin/master

mac_build:
  stage: build
  tags:
    - mac
  artifacts:
    paths:
<<<<<<< HEAD
      - ./openfpm_data/build/src/mem_map
=======
      - ./openfpm_io/build/src/io
      - ./openfpm_io/test_data
>>>>>>> origin/master
  script:
    - ./build.sh $CI_PROJECT_DIR $CI_RUNNER_TAGS NO $CI_COMMIT_REF_NAME

mac_run:
  stage: test
  tags:
    - mac
  dependencies:
    - mac_build
  script:
<<<<<<< HEAD
    - ./openfpm_data/build/src/mem_map 
=======
    - ./run.sh $CI_PROJECT_DIR $CI_RUNNER_TAGS NO $CI_COMMIT_REF_NAME
>>>>>>> origin/master

ubuntu_build:
  stage: build
  tags:
    - ubuntu
  artifacts:
    paths:
<<<<<<< HEAD
      - ./openfpm_data/build/src/mem_map
=======
      - ./openfpm_io/build/src/io
      - ./openfpm_io/test_data
>>>>>>> origin/master
  script:
    - ./build.sh $CI_PROJECT_DIR $CI_RUNNER_EXECUTABLE_TAGS NO $CI_COMMIT_REF_NAME

ubuntu_run:
  stage: test
  tags:
    - ubuntu
  dependencies:
    - ubuntu_build
  script:
<<<<<<< HEAD
    - ./openfpm_data/build/src/mem_map

=======
    - ./run.sh $CI_PROJECT_DIR $CI_RUNNER_TAGS NO $CI_COMMIT_REF_NAME
>>>>>>> origin/master
